language: node_js
node_js:
- 8
deploy:
  provider: heroku
  api_key:
    secure: ts+9qXpbKk0T8GBX1y9rD1D0G19tuy4Q8nxLz8FTf5WHB3MLCUUq4xqNLyFI1JZHasGwgWZyrQ9dSJU9I7iKBlRsf8T+KelTMGxa/4YvVO8YPu4Hs7TV3hcvgsFw2DITDwuwqynOb7KH9MLcW7dZ93sWC6NdppHUQy+NJ4jGkB+jCEFeJ61S2DsO9uKD3Kfkj37sS1gmcNGRTwXRK2flapZ31lPgAfkhnfpUmm1+sSPEwiJ3Fmjwz3RHsB2BfIMDnjQ9ZhUJtfNPbP8PUYv/o+XurnCqmY+WRke17BEHqSECwr+3tMI+vsGS30OoECA7ICNQXc8Q0M/B+c2x19/3aMD3EoVkd0m0mDbg1VfpyEbBk3tJXKNPC4xO1eD898vvwvbRSGeVDRX4iFPBksoRGVueLBjbqyHHELsVLDQH1tp2dLf2piOnugnnznj1SVOFSJ0EvUahk2pc7HpcQdYOkiiDlzTHGpTPF20rlI3XbFF1kySyjlDIMzD7h+x7ALgjRhEjQ8rzQ6+6nuXYYkhQbM990Y28ln+6FnB3pSGOwKMUr4gcFENpLacgysR8aXuwIWCxf0ESQjQvCyGxeMIJ86+UhZrAvtpt+wCtTUnxpVGp4+ihck/QV0lM/KkUu61YHGsa5ijhWrfA2dYP8J9eGZv/y0trn4sMuOXuLou4+xE=
  app: damp-plains-73885
  on:
    repo: looneywebdev/looneyhealth
  api:
    key:
      secure: DzypAxxELbwFK4mHSnjrKyYOXS7iZayGq5MCKHevA5rFmI68KHyOfwmburPiIQRGzdd9RXkutf2kgUUk7tjI9FKLJZzbqHk8ApmSCP/BgYzWwirB81fMdXMFC8qnGg2aVLUXqW2Z3j9i1i7k9r/3tFNaRRJIoMu6j1GysBH6DzaJOzVHC42SEbNrv94tozfldd30FHClDvpwcYd/+QET7Qkniy0QxFKg4Po2lUN1e9qirLJWd3CMyidZIPQ+nDmJOGfdYC55BFgxbwSomot3nY1UgKItDF6XtqJ8oq+SFvFbEA17OLatvrgQCkIirFGcg/LYzNVQ7+SxuC8LDBkchDMvQoFmtlj4hfBlVSKkMwvsMjAaUgIfaL1jh2cfvKdHhc67ubmPUciAg1einwJ4vHm2BknvrMmmPjJFjYNxi5IIkWACg00pFAULBe2Ta0BYUPwPLvIewX2oWQNELucRUJQ5g1FXjNhq77yVA8/yUWqqFTmc1ecWCpRwVd4JpXTP+Z6BRP/S8egbJ9C+QsIf7MKCQeAyGPvAtvVYpDLdL4H5Ljcg+Xma8PaBgYP0ewzx3mhsJIzBGW3G3IHXWv4EMmBsS3FVWOx9WH+LETJNmn+aj72/Ss7X97utjabcG2u85s4c+pEkyEaF5KQjNp4av7d15UHGGtAxw9/90A6MbUU=
